### ISSUE TITLE
search result not link ?

### ISSUE THREAD

**Issue by Freecey** [Freecey/Bulletin-Board-Project#57]
**Describe the bug**
search result link do nothing

**To Reproduce**
1. Go to 'search type a word'
2. Click on 'try to click on result'
3. no link

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 lts
 - Browser Chromium
 - Version 86

**Comment by KevKsar** [comment]
the links to the different search results have been added

**Comment by KevKsar** [comment]
the links to the different search results have been added
