### ISSUE TITLE
Bug Announce by on topics.php

### ISSUE THREAD

**Issue by Freecey** [Freecey/Bulletin-Board-Project#76]
**Describe the bug**
Announce by on topics.php don't display the good information

**Screenshots**
![Screenshot from 2020-11-28 16-28-33](https://user-images.githubusercontent.com/71413240/100519217-d0086a80-3196-11eb-96e2-ac234f791980.png)
![Screenshot from 2020-11-28 16-29-08](https://user-images.githubusercontent.com/71413240/100519222-e0204a00-3196-11eb-88c1-06c5e76ec1dd.png)

**Comment by macmowl** [comment]
I am checking this part.

**Comment by Freecey** [comment]
not a bug display the last edit users not the author
